

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : "ssh Into the system"
        run : |
         echo "${{ vars.KEY }}" >> key.pem
         echo "haider"
         cat key.pem
         chmod 600 key.pem
         ssh-keygen -y -f key.pem

         ssh -i key.pem -o StrictHostKeyChecking=no Hp@136.115.207.167
